### ISSUE TITLE
[기능 요청] 버튼에 hover할시 색깔이 너무 빨리 바뀌는거 같습니다

### ISSUE THREAD

**Issue by zero734kr** [koreanbots/koreanbots#12]
![image](https://user-images.githubusercontent.com/51540538/80873644-7091bd00-8c90-11ea-81a4-671566c98534.png)

## 재현방법
버튼에 마우스 커서를 올려두기

## 원하는 동작
0.2초 정도로 천천히(?) 색깔이 바뀌는거 나을듯 합니다
(
css에 
```css
<selection>:hover {
    color: 색깔;
    transition: 0.2s
}
```
로 적으면 해결될거 같습니다.
)

## 발생한 문제
제가 불편합니다

## 클라이언트 버젼
![image](https://user-images.githubusercontent.com/51540538/80874338-d8480800-8c90-11ea-8f09-b54ed213182d.png)

## 사양
OS: Linux Mint 19.3 Tricia 
Chrome 버젼: Google Chrome 81.0.4044.122

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그(버그가 아닙니다)를 다시 발생시킬 수 있나요?
